{
   "workingDirectory":[""],
   "executionTimeout":["300"],
   "commands":[
      "sudo su",
      "# Sleep because we are not exactly sure when this will be triggered, maybe Ec2 is not ready.",
      "sleep 180",
      "mkdir -p /tmp/keys",
      "aws s3 cp s3://${aws_account_id}-keys/keys /tmp/keys --recursive",
      "for user_key in /tmp/keys/*; do",
      " if ! id -u $user_key > /dev/null 2>&1; then",
      " sudo adduser $(basename -- $user_key)",
      " mkdir -p /home/$(basename -- $user_key)/.ssh",
      " touch /home/$(basename -- $user_key)/.ssh/authorized_keys",
      " cp $user_key /home/$(basename -- $user_key)/.ssh",
      " cat /home/$(basename -- $user_key)/.ssh/$(basename -- $user_key) > /home/$(basename -- $user_key)/.ssh/authorized_keys",
      " chmod 700 /home/$(basename -- $user_key)/.ssh",
      " chmod 600 /home/$(basename -- $user_key)/.ssh/authorized_keys",
      " chown $(basename -- $user_key):$(basename -- $user_key) /home/$(basename -- $user_key)/.ssh",
      " chown $(basename -- $user_key):$(basename -- $user_key) /home/$(basename -- $user_key)/.ssh/authorized_keys",
      " # Add user to wheel group (sudo)",
      " usermod -aG wheel $(basename -- $user_key)",
      " # Disable password for sudo users",
      " echo \"\" >> /etc/sudoers",
      " echo \"$(basename -- $user_key) ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers",
      " rm /home/$(basename -- $user_key)/.ssh/$(basename -- $user_key) -f",
      " echo \"User $(basename -- $user_key) successfully created.\"",
      " else",
      " echo \"User $(basename -- $user_key) already exists\"",
      " fi",
      "done",
      "",
      "# Cleanup tmp keys folder",
      "rm -rf /tmp/keys"
   ]
}